name: Lint

on: [push]

jobs:
  xml-linters:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install xmllint
      run: sudo apt-get install -y libxml2-utils
    - name: XML Lint
      run: xmllint --schema default.xsd default.xml
